/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Pascal Helbig' at '04.11.16 12:59' with Gradle 2.8
 *
 * @author Pascal Helbig, @date 04.11.16 12:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void someNotUsedMethod() {
        System.out.println("call me maybe...");
    }
}
