import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Pascal Helbig' at '04.11.16 12:59' with Gradle 2.8
 *
 * @author Pascal Helbig, @date 04.11.16 12:59
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testSomeNotUsedMethod() {
        Library classUnderTest = new Library();
        assertEquals("call me maybe...", "call me maybe...", classUnderTest.someNotUsedMethod());
    }
}
